version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hackgrowth_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: hackgrowth_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    ports:
      - '35432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: hackgrowth_redis
    restart: unless-stopped
    ports:
      - '36379:6379'
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
