export const YOUTUBE_CONSTANTS = {
  EMBED_BASE_URL: 'https://www.youtube.com/embed/',
} as const;

export const PRISMA_ERROR_CODES = {
  UNIQUE_CONSTRAINT_VIOLATION: 'P2002',
  FOREIGN_KEY_CONSTRAINT_FAILED: 'P2003',
  CONSTRAINT_FAILED: 'P2004',
  INVALID_ID: 'P2014',
  REQUIRED_FIELD_MISSING: 'P2011',
  MISSING_REQUIRED_FIELD: 'P2012',
  TABLE_NOT_FOUND: 'P2021',
  COLUMN_NOT_FOUND: 'P2022',
  RECORD_NOT_FOUND: 'P2025',
} as const;

export const TRANSACTION_CONSTANTS = {
  TIMEZONE: '+07:00',
  EXPIRY_DURATION_MINUTES: 1440, // 24 hours
  EXPIRY_DURATION_HOURS: 24,
  PPN_RATE: 0.11, // 11% PPN Indonesia
  PLATFORM_FEE_RATE: 0.10, // 10% Platform Fee
} as const;
